theme: jekyll-theme-minimal
title: ODF/DOCX Scan for Zotero
description: Bringing Zotero citations to any word processor
github:
  repository_url: "https://github.com/Juris-M/zotero-odf-scan-plugin"
  project_title: "Juris-M/zotero-odf-scan-plugin"
  owner_name: "Sebastian Karcher"
  owner_url: "https://sebastiankarcher.com"
