pref("extensions.zotero.export.lastStyle", 'http://www.zotero.org/styles/chicago-note-bibliography');
pref("extensions.zotero.rtfScan.lastInputFile", "");
pref("extensions.zotero.rtfScan.lastOutputFile", "");
pref("extensions.zotero.odfScan.lastInputFiletocitations", "");
pref("extensions.zotero.odfScan.lastOutputFiletocitations", "");
pref("extensions.zotero.odfScan.lastInputFiletomarkers", "");
pref("extensions.zotero.odfScan.lastOutputFiletomarkers", "");
pref("extensions.zotero.rtfScan.fileType", "rtf");
pref("extensions.zotero.rtfScan.outputMode", "");
